### ISSUE TITLE
Post pictures of your pets <3

### ISSUE THREAD

**Issue by ran-maciej-idzikowski** [department-for-transport/git-and-github-training#101]
* **Is your feature request related to a problem? Please describe.**

More pics!

* **Describe the solution you'd like**

More pics!

* **Describe alternatives you've considered**

None.

* **Additional context**

This is my dog called Banana.
![banana](https://github.com/department-for-transport/git-and-github-training/assets/131355035/ae3ab037-f9dc-4760-9d10-f4d9d2a92360)

**Comment by David-P-5** [comment]
GDPR, do you have the dogs approval?

**Comment by RA-Manisha-Jundoosingh** [comment]
@ran-maciej-idzikowski I like this suggestion!

**Comment by akshaybhandariDFT** [comment]
please assign the dog to this issue. asking for a friend

**Comment by JamesTaylor2DfT** [comment]
![Unhelpful idiots](https://github.com/department-for-transport/git-and-github-training/assets/123000322/ef9ddcc4-069d-4b74-a25f-8f490e53aad6)
![Return to sender](https://github.com/department-for-transport/git-and-github-training/assets/123000322/07cd86db-97a6-40db-86cf-218bc88faae0)

**Comment by felixivers** [comment]
![Slovenia Train](https://github.com/department-for-transport/git-and-github-training/assets/129416281/56b47b26-41cf-4afb-9b4c-8a6598a7f1ef)
The only pics I have on here are of trains :(
