### ISSUE TITLE
Laptop crashing when running code

### ISSUE THREAD

**Issue by ethanjkendall** [department-for-transport/git-and-github-training#125]
* **Describe the bug**

When reaches line 56 of code, laptop crashes.

* **Tell us how to reproduce the error**

1. Run code
2. Wait until line 56
3. Crash

* **Expected behavior**

* **Platform**

Were you running the code on:

- [X] Local R
- [ ] Citrix
- [ ] Non-network laptop

* **Screenshots**

**Comment by LRTA-Kieran-Brown** [comment]
Fixed it mate - you're welcome
