### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by LRTA-Kieran-Brown** [department-for-transport/git-and-github-training#128]
* **Describe the bug**

BM @ 4.30? 

* **Tell us how to reproduce the error**

* **Expected behavior**

* **Platform**

Were you running the code on:

- [ ] Local R
- [ ] Citrix
- [ ] Non-network laptop

* **Screenshots**

**Comment by LawrenceGreenRA** [comment]
This bug does not need fixing - I accept.
