### ISSUE TITLE
Limitations of code

### ISSUE THREAD

**Issue by LRTA-Manu-Tiwary** [department-for-transport/git-and-github-training#149]
* **Is your feature request related to a problem? Please describe.**

would like a new feature to be able to automatically get everyone to the social this Thursday

* **Describe the solution you'd like**

would like social sec to be able to force everyone there @Iona-MacKinnon @LRTA-Kieran-Brown  please fix

* **Describe alternatives you've considered**

* **Additional context**

**Comment by AAD-Jordan-Low** [comment]
I think you might be able to use the function `enforce_fun(who = c("LRTA"))`

**Comment by Iona-MacKinnon** [comment]
Lol I can't even make it :(

**Comment by LRTA-Kieran-Brown** [comment]
[https://media.giphy.com/media/QsyPRpG6WVR6SYfBVw/giphy.gif](url)

**Comment by LRTA-Kieran-Brown** [comment]
[](https://media.giphy.com/media/QsyPRpG6WVR6SYfBVw/giphy.gif)

**Comment by LRTA-Manu-Tiwary** [comment]
https://media.giphy.com/media/xT5LMJEgNVGGYUTTGM/giphy.gif

Manu Tiwary  | , , Department for Transport
|  07977695552 |

**Comment by LRTA-Kieran-Brown** [comment]
![]https://media.giphy.com/media/QsyPRpG6WVR6SYfBVw/giphy.gif
