### ISSUE TITLE
Run out of biscuits

### ISSUE THREAD

**Issue by caityrice** [department-for-transport/git-and-github-training#165]
**Not enough biscuits today**

I should have brought more biscuits to work

* **Tell us how to reproduce the error**

1. Forgot to buy
2. Had no biscuits

* **Expected behavior**
![Bourbon_Biscuits1](https://github.com/department-for-transport/git-and-github-training/assets/142881104/bb01a66c-bd43-4389-ad6b-4fa8d4161be0)

Have biscuits, eat biscuits

* **Platform**

Were you running the code on:

- [ ]  laptop

* **Screenshots**

**Comment by josef-stadter** [comment]
Heck

**Comment by mirandamathieson** [comment]
:hugs:

**Comment by Seymiotics** [comment]
devastating please rectify this now!!!!

**Comment by TRENDS-ScottFox** [comment]
What sort of biscuits though?!

**Comment by Paul-McEvoy** [comment]
Can you access the cookies on your browser?
