### ISSUE TITLE
please can i have a coffee

### ISSUE THREAD

**Issue by Seymiotics** [department-for-transport/git-and-github-training#170]
**currently the code does not solve my issue of wanting a drink.**

I'm always frustrated when i don't have a drink.

please can somebopdy make me one.

i have considered dying of thirst.

**Comment by caityrice** [comment]
Sending positive coffee thoughts...

**Comment by mirandamathieson** [comment]
☕ ☕ ☕

**Comment by josef-stadter** [comment]
[https://tenor.com/en-GB/view/no-thatcher-no-no-no-gif-12956242](url)
