### ISSUE TITLE
My code is perfect R is clearly the issue

### ISSUE THREAD

**Issue by Paul-McEvoy** [department-for-transport/git-and-github-training#177]
* **Is your feature request related to a problem? Please describe.**

I have written beautiful code, R is the problem. 

* **Describe the solution you'd like**
@caityrice Fix R

* **Describe alternatives you've considered**
Throwing laptop out window
Shouting at screen
* **Additional context**

**Comment by caityrice** [comment]
I would go with the laptop out the window option personally
