### ISSUE TITLE
Create an Award ceremony in the training 

### ISSUE THREAD

**Issue by EwanDevineKennedy** [department-for-transport/git-and-github-training#197]
* **Is your feature request related to a problem? Please describe.**

This training resources would benefit from awards

* **Describe the solution you'd like**

please create some awards

* **Describe alternatives you've considered**

doing it via email

* **Additional context**

**Comment by DIPAD-Fran-Bryden** [comment]
🥇

**Comment by EwanDevineKennedy** [comment]
@AIMS-Edisa-Livingstone

**Comment by EwanDevineKennedy** [comment]
a good place to add the code is here https://github.com/department-for-transport/git-and-github-training/blob/ca14392f2281545a09983af37f4c28fb0c494845/functions.R#L45-L55

this feature would be a useful prize #196

**Comment by jsdalgetyLRTA** [comment]
I think monetary rewards would go down well
