### ISSUE TITLE
New feature to do perform some imaginary additional checks.

### ISSUE THREAD

**Issue by AIMS-Edisa-Livingstone** [department-for-transport/git-and-github-training#199]
* **I need to perform some extra imaginary checks on a dataset.**

I am always frustrated when the data ingested earlier doesn't have a certain attribute.

* **Describe the solution you'd like**

A line is printed to confirm the data has the attribute

* **Describe alternatives you've considered**

Not sure

* **Additional context**

Blah blah blah

**Comment by AIMS-Edisa-Livingstone** [comment]
I have added some imaginary checks to a file. Does this seem OK to you @zmahmood98 .

**Comment by isabellaimage** [comment]
Hello @AIMS-Edisa-Livingstone and @zmahmood98.  I am randomly adding a comment to show I know how to add a comment

**Comment by AIMS-Edisa-Livingstone** [comment]
I am pretending to add a suitable reference #196
