### ISSUE TITLE
Interactive chart not available

### ISSUE THREAD

**Issue by TASM-Ilianna-Pirounaki** [department-for-transport/git-and-github-training#213]
* **Is your feature request related to a problem? Please describe.**

The interactive version of bubble charts is not working properly and we need to find a workaround. 

* **Describe the solution you'd like**

Combine different charts to make an interactive bubble chart.

* **Describe alternatives you've considered**

Having a different type of chart, but I don't like it. 

* **Additional context**

**Comment by TASM-Ilianna-Pirounaki** [comment]
@EHENDERS1 Any ideas? 😄 🌈

**Comment by EHENDERS1** [comment]
Bubble charts sounds awesome! I need to find out how to create them 📈 😄
