### ISSUE TITLE
Hot chocolate Fridays

### ISSUE THREAD

**Issue by EHENDERS1** [department-for-transport/git-and-github-training#214]
* **Is your feature request related to a problem? Please describe.**

Hot chocolate in the office on Fridays.

* **Describe the solution you'd like**

A cup of hot chocolate for everyone delivered by robots.

* **Describe alternatives you've considered**

Not working on Fridays.

* **Additional context**

I really like hot chocolate. 
<img width="70" alt="robot" src="https://github.com/department-for-transport/git-and-github-training/assets/157044729/17728fb4-fb2a-48e7-98ee-e5aabb1edcae">

**Comment by Seymiotics** [comment]
full support

**Comment by EHENDERS1** [comment]
😆
