### ISSUE TITLE
Getting Email Saving Code to save attatched MEP's and 1YA reports.

### ISSUE THREAD

**Issue by SeanDFT** [department-for-transport/git-and-github-training#218]
* **Is your feature request related to a problem? Please describe.**

I noticed in email_search.R is that only saves very specific attatchements that the coder expects to be in email. Can we expand this to include other options, like MEP and 1YA reports

* **Describe the solution you'd like**

I think we should two extra code chunks to this section, one to save attatched MEPs, the other to save 1YA reports.

https://github.com/department-for-transport/git-and-github-training/blob/ca14392f2281545a09983af37f4c28fb0c494845/email_search.R#L63-L80

* **Describe alternatives you've considered**

The main alternative I have considered is amending the code to accept any attachment. While I cannot rule this out on technical grounds, I cannot conceive of how it would be done.

* **Additional context**
![image](https://github.com/department-for-transport/git-and-github-training/assets/158047209/c38c95ee-edaa-4e6f-9b8e-ff867aa8c50d)

**Comment by EHENDERS1** [comment]
I like your meme 😆
