### ISSUE TITLE
No puppies in code comments

### ISSUE THREAD

**Issue by DIPAD-Fran-Bryden** [department-for-transport/git-and-github-training#235]
* **Describe the bug**

I think there should be more puppy pictures in the code

* **Tell us how to reproduce the error**

1. Read code
2. Observe lack of puppies

* **Expected behavior**

I expect to see puppies when I code

* **Platform**

Were you running the code on:

- [ ] Local R
- [X] Citrix
- [ ] Non-network laptop

* **Screenshots**

**Comment by DIPAD-Fran-Bryden** [comment]
@avasharma See issue #47

**Comment by avasharma** [comment]
![download](https://github.com/user-attachments/assets/8e1a7842-5833-4c8c-85c1-ab0461e1c5d3)

**Comment by DIPAD-Fran-Bryden** [comment]
Example code: https://github.com/department-for-transport/git-and-github-training/blob/b140dd1d8b1919c924184bba4cda5964e78aac14/functions.R#L2-L8
