### ISSUE TITLE
Too many puppies

### ISSUE THREAD

**Issue by SOMARA-DFT** [department-for-transport/git-and-github-training#237]
* **Is your feature request related to a problem? Please describe.**

too many puppy pictures

* **Describe the solution you'd like**

Less puppy pictures

* **Describe alternatives you've considered**

Replace with ferrets 

* **Additional context**

![image](https://github.com/user-attachments/assets/482d5f3a-9160-438d-b05c-a016be3282e9)

**Comment by ACordesCRD** [comment]
Nice ferret :)

**Comment by SOMARA-DFT** [comment]
[https://github.com/department-for-transport/git-and-github-training/pull/250](url)

**Comment by aleaciamorbi** [comment]
Puppies forever <3
