### ISSUE TITLE
Adding drop down images 

### ISSUE THREAD

**Issue by ACordesCRD** [department-for-transport/git-and-github-training#238]
* **Is your feature request related to a problem? Please describe.**

I would like a way of having drop down images for the most common types of modes of transport. 

* **Describe the solution you'd like**

Let me have some code and some stock images which I can add royalty free . 

* **Describe alternatives you've considered**

I've tried googling it 

* **Additional context**

I need help by 10pm tonight due to internal deadlines  

@avasharma - please help

**Comment by avasharma** [comment]
Have you tried adding drop down images?
