### ISSUE TITLE
Laptop explodes when opening R

### ISSUE THREAD

**Issue by avasharma** [department-for-transport/git-and-github-training#239]
* **Description of bug**

Laptop go boom when opening R.

* **Tell us how to reproduce the error**

1. Open R
2. Explode

* **Expected behavior**

Laptop does not explode.

* **Platform**

Were you running the code on:

- [X] Local R
- [ ] Citrix
- [ ] Non-network laptop

* **Screenshots**

![R](https://github.com/user-attachments/assets/64e033bd-961e-43d4-b362-d78ebe47d74c)

**Comment by BenRickard1** [comment]
Don't think that's supposed to happen but not sure...

**Comment by avasharma** [comment]
> Don't think that's supposed to happen but not sure...

I think you might be right :(

**Comment by ManiScriptWizard** [comment]
@avasharma, that is scary...

- [ ] Do you have a file extinguisher? 

- [ ] if everything fails, run

**Comment by h-sleight** [comment]
Have you tried switching it off and on again?

**Comment by avasharma** [comment]
> Have you tried switching it off and on again?

No but good idea, I'll try that next

**Comment by avasharma** [comment]
> @avasharma, that is scary...
> 
> * [ ]  Do you have a file extinguisher?
> * [X ]  if everything fails, run
