### ISSUE TITLE
Adding a pacman style game

### ISSUE THREAD

**Issue by ManiScriptWizard** [department-for-transport/git-and-github-training#241]
* **Is your feature request related to a problem? Please describe.**
no 

Can we add links to games in the code to motivate to take stress bursting break

* **Describe the solution you'd like**
* Perhaps a game like this?
[https://www.google.com/imgres?q=pacman&imgurl=https%3A%2F%2Fblog.sciencemuseum.org.uk%2Fwp-content%2Fuploads%2F2017%2F10%2FPacman-400x250.gif&imgrefurl=https%3A%2F%2Fblog.sciencemuseum.org.uk%2Fpac-man-turns-40%2F&docid=Nc3COqIXMEdkpM&tbnid=odYPGflD-2mt5M&vet=12ahUKEwia9J_xnL2HAxXYUkEAHb9YFPgQM3oECBkQAA..i&w=400&h=250&hcb=2&ved=2ahUKEwia9J_xnL2HAxXYUkEAHb9YFPgQM3oECBkQAA](URL)

![image](https://github.com/user-attachments/assets/c65018e9-dffd-4b7c-b6f1-4cae2938d509)

* **Describe alternatives you've considered**

* **Additional context**

**Comment by yooanean** [comment]
love this game
what about [https://trex-runner.com/](url)

**Comment by avasharma** [comment]
This is a great idea, why stop there?
