### ISSUE TITLE
lack of images

### ISSUE THREAD

**Issue by Dipad-imrankhan** [department-for-transport/git-and-github-training#242]
* **Describe the bug**

want to see images in table

1. check code
2. check missing image 

* **Expected behavior**

image in table

* **Platform**

Were you running the code on:

- [x] Local R
- [ ] Citrix
- [ ] Non-network laptop

* **Screenshots**

**Comment by ManiScriptWizard** [comment]
try issue #241 

example code: https://github.com/department-for-transport/git-and-github-training/blob/b140dd1d8b1919c924184bba4cda5964e78aac14/functions.R#L2
