### ISSUE TITLE
Create a connection between Github and GCP

### ISSUE THREAD

**Issue by h-sleight** [department-for-transport/git-and-github-training#243]
* **Is your feature request related to a problem? Please describe.**

We currently only use Github as an archive and not as version control due to lack of connection with GCP

* **Describe the solution you'd like**

A connection between GCP and Github like R

* **Describe alternatives you've considered**

Letting my team go wild and never saving their code

* **Additional context**
[
[Add any other context or screenshots about the feature request here.](url)](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExODlhbTlucTZ0bGJyM3NuMTNzZHFrODdiZGlvZTVwcWxvdzlmaXhpdyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/8p8E1sylIARDW/giphy.gif)

**Comment by TRENDS-maggie-alexiadou** [comment]
Great gif!!
