### ISSUE TITLE
I can't think of a bug :/

### ISSUE THREAD

**Issue by TRENDS-maggie-alexiadou** [department-for-transport/git-and-github-training#244]
* **Github training example bug**

This is an example bug for training purposes.

* **Tell us how to reproduce the error**
1. I can't think of any steps :/

* **Expected behavior**

Someone please give me a bug idea :')

* **Platform**

Were you running the code on:

- [Yes] Local R
- 
* **Screenshots**

![no+idea+animation+storyboard8](https://github.com/user-attachments/assets/24745e0e-758c-47e0-ab06-c9972412f356)

**Comment by BenRickard1** [comment]
Have you considered widening your search to insects?
