### ISSUE TITLE
My R code is making my head hurt

### ISSUE THREAD

**Issue by HannahCurtis2024** [department-for-transport/git-and-github-training#259]
* **Is your feature request related to a problem? Please describe.**

Yes, my brain is the problem.

* **Describe the solution you'd like**

To become an R whizz 

* **Describe alternatives you've considered**
Crying
Eating lots of chocolate 

* **Additional context**
Help

**Comment by CatherineMottramCAO** [comment]
I recommend chocolate and asking @sbridonneau  to help
