### ISSUE TITLE
Need more cat pictures in the project files

### ISSUE THREAD

**Issue by JBOTTOML** [department-for-transport/git-and-github-training#260]
* **Is your feature request related to a problem? Please describe.**

The project files don't have enough images

* **Describe the solution you'd like**

More pictures of cats would improve engagement with this project

* **Describe alternatives you've considered**

Pictures of dogs, fish, elephants or tigers

* **Additional context**

**Comment by JBOTTOML** [comment]
@sbridonneau I understand you have a cat, can you help?

**Comment by CRD-Monica-Li** [comment]
@JBOTTOML - have you considered adding sasquatches?
