### ISSUE TITLE
Code to answer emails

### ISSUE THREAD

**Issue by CatherineMottramCAO** [department-for-transport/git-and-github-training#261]
* **Is your feature request related to a problem? Please describe.**

This is a request for a new feature 

* **Describe the solution you'd like**

I want an automated replies to all my emails for the past 3 months to be sent and the emails to then be deleted so that I have a clean inbox

* **Describe alternatives you've considered**
I have considered actually reading all my emails and addressing the issues raised but frankly I cannot be bothered

* **Additional context**

My inbox is overloaded, I need help

**Comment by JBOTTOML** [comment]
Yes please we need this feature!

**Comment by CatherineMottramCAO** [comment]
@JBOTTOML can you help with this?

**Comment by CatherineMottramCAO** [comment]
Or maybe its more @HannahCurtis2024's area of expertise?

**Comment by HannahCurtis2024** [comment]
I will get back to you in 2-5 business days :P
