### ISSUE TITLE
Add data for Scotland

### ISSUE THREAD

**Issue by CRD-Monica-Li** [department-for-transport/git-and-github-training#263]
* **Is your feature request related to a problem? Please describe.**

The chart would look better if Scotland's data was included.

* **Describe the solution you'd like**

Add data for Scotland.

* **Describe alternatives you've considered**

Leaving the chart as it is and explaining why data for Scotland is missing.

* **Additional context**

**Comment by SimonBottomley** [comment]
Can we also include Wales and the Channel Islands?

**Comment by JBOTTOML** [comment]
As another suggested alternative, we could make Scotland independent so we don't have to report their data
