### ISSUE TITLE
Taran's feature request for better coffee

### ISSUE THREAD

**Issue by TRENDS-Taran-Uppal** [department-for-transport/git-and-github-training#280]
* **Is your feature request related to a problem? Please describe.**

The coffee comes in one standard flavour

* **Describe the solution you'd like**

A variety of coffee flavour offerings

* **Describe alternatives you've considered**

Bringing in tea or coffee flavours
Buying fun coffee

* **Additional context**

@LAURMURPH may also want nice coffee

**Comment by AMBA-Hannah-Kirrane** [comment]
I agree with better coffee, and I'd also suggest adding hot chocolate!

**Comment by LAURMURPH** [comment]
Free Espresso would be better
