### ISSUE TITLE
I would like a way to interact with this repository in VR

### ISSUE THREAD

**Issue by frankie-t-h** [department-for-transport/git-and-github-training#281]
* **Is your feature request related to a problem? Please describe.**

No apart from the fact that I think VR is kool unless my eyes are blurry

* **Describe the solution you'd like**

I would like a fully documented API around user interaction and how different gestures will navigate the user through files and folders. I want it to reflect the one they use in minority report.

* **Describe alternatives you've considered**

Using the command line or a network connected drone

* **Additional context**

Lawnmower man and jurrassic park have mainframe interactions I'd like to reference and of course minority report.

**Comment by frankie-t-h** [comment]
Hi @CTUCKER0900  thought you might like to look into this issue

**Comment by CTUCKER0900** [comment]
You are absolutely right of course
