### ISSUE TITLE
Adding an extra Y-Axis - Made up Example

### ISSUE THREAD

**Issue by CTUCKER0900** [department-for-transport/git-and-github-training#282]
* **Is your feature request related to a problem? Please describe.**

An example training exercise of a feature request addition for made-up data.

* **Describe the solution you'd like**

Imaginary scenario - adding an extra y-axis showing percentage change. 

* **Describe alternatives you've considered**

None, just a suggestion!!

* **Additional context**

No screenshots because this is a made-up scenario.

**Comment by DfT-Jack-Casey** [comment]
@CTUCKER0900 we should definitely add this y-axis!
