### ISSUE TITLE
Pink charts only

### ISSUE THREAD

**Issue by AMBA-Hannah-Kirrane** [department-for-transport/git-and-github-training#283]
* **Is your feature request related to a problem? Please describe.**

This repo has charts that aren't pink, and they don't look nice.

* **Describe the solution you'd like**

I want all the charts in this repo to use the RdPu colour palette.

* **Describe alternatives you've considered**

I have considered blue charts but they wont be as pretty.

* **Additional context**

Pink is my favourite colour!

**Comment by AMBA-Hannah-Kirrane** [comment]
@frankie-t-h do you agree with pink charts or prefer blue?

**Comment by DfT-Jack-Casey** [comment]
I prefer green!
