### ISSUE TITLE
Jack feature request

### ISSUE THREAD

**Issue by DfT-Jack-Casey** [department-for-transport/git-and-github-training#284]
* **Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. Ex. I'm always frustrated when the code goes wrong

* **Describe the solution you'd like**

Somebody to help me solve it

* **Describe alternatives you've considered**

Doing another training course!

* **Additional context**

@frankie-t-h

**Comment by frankie-t-h** [comment]
Thanks for the offer of work @DfT-Jack-Casey 

What is it that you would like to request, I am not sure whether there is a new feature you would like.

If it's that the code goes wrong have you considered working with copilot?

**Comment by frankie-t-h** [comment]
https://m.media-amazon.com/images/I/61GoAvNaZSL.__AC_SX300_SY300_QL70_ML2_.jpg

Is this the type of Jack you would like to feature or is the Jack mentioned you :D

(troll)[https://m.media-amazon.com/images/I/61GoAvNaZSL.__AC_SX300_SY300_QL70_ML2_.jpg]
