### ISSUE TITLE
Laura's bug

### ISSUE THREAD

**Issue by LAURMURPH** [department-for-transport/git-and-github-training#286]
My laptop can't hold a connection @frankie-t-h

**Comment by frankie-t-h** [comment]
Please add this timer code to your repository and it will fix itself in a magical way:


/* globals Shiny,Audio */
--
2 | class CountdownTimer {
3 | constructor (el, opts) {
4 | if (typeof el === 'string' \|\| el instanceof String) {
5 | el = document.querySelector(el)
6 | }
