### ISSUE TITLE
Spring clean (Oct 2024)

### ISSUE THREAD

**Issue by sbridonneau** [department-for-transport/git-and-github-training#297]
This repo could do with the following (although given it's a training repo, it might not all be appropriate)
* set up renv
* remove stale branches
* clear old PRs and Issues (but this might be useful as examples)

**Comment by TRENDS-Rachel-Avbulimen** [comment]
I have removed stale branches, and have removed most of the PRs and Issues. Left 1 or 2 for examples to use for the training.
