### ISSUE TITLE
not enough espresso in git

### ISSUE THREAD

**Issue by aleaciamorbi** [department-for-transport/git-and-github-training#298]
* **Is your feature request related to a problem? Please describe.**

Coding needs coffee

* **Describe the solution you'd like**

espresso on hand

* **Describe alternatives you've considered**

no alternatives acceptable

* **Additional context**

**Comment by AMBA-Junaiy-Chowdhury** [comment]
https://www.bing.com/search?pglt=41&q=coffee+machines&cvid=8ede3a3d8e974aeb8e46bcc2a6560048&gs_lcrp=EgRlZGdlKgcIABAAGPkHMgcIABAAGPkHMgYIARBFGDkyBggCEAAYQDIGCAMQABhAMgYIBBAAGEAyBggFEAAYQDIGCAYQABhAMgYIBxAAGEAyBggIEAAYQDIICAkQ6QcY_FXSAQgyNjE2ajBqMagCALACAA&FORM=ANNAB1&PC=U531
