### ISSUE TITLE
Add smiley faces

### ISSUE THREAD

**Issue by olivermiddlemasdft** [department-for-transport/git-and-github-training#303]
* **Is your feature request related to a problem? Please describe.**

I don't like the lack of emotion expressed in the text files

* **Describe the solution you'd like**

Add smiley faces into the text files e.g. :)

* **Describe alternatives you've considered**

No alternatives, we must have smiley faces

* **Additional context**

Makes me happy, I'm sure @TASM-ines-heimann would prefer it

**Comment by TASM-ines-heimann** [comment]
Thanks, I love smileys!
