### ISSUE TITLE
Please add more pictures of dogs

### ISSUE THREAD

**Issue by TASM-Robyn-Smith** [department-for-transport/git-and-github-training#69]
* **Is your feature request related to a problem? Please describe.**

This code is not as engaging as it could be. People are not concentrating when running it.

* **Describe the solution you'd like**

A random picture of a dog should appear after each code run. This should be sampled from a repository of dog photos that can be added to by members of staff.

* **Describe alternatives you've considered**

I've considered cats but they just aren't good enough.

* **Additional context**

This has been signed off and made top priority by the SRO.

**Comment by ran-maciej-idzikowski** [comment]
Here's my dog <3 
![banana](https://github.com/department-for-transport/git-and-github-training/assets/131355035/96ca6ac6-6094-4123-a88b-213a4463a62e)
