### ISSUE TITLE
Add free coffee pls

### ISSUE THREAD

**Issue by IMAdft2** [department-for-transport/git-and-github-training#96]
* **Is your feature request related to a problem? Please describe.**
Yes but no
I'm frustrated when a cup of coffee does not materialize when I run the code
* **Describe the solution you'd like**
Free coffee
idk just fix pls
* **Describe alternatives you've considered**
Not drinking coffee
Drinking tea instead
* **Additional context**
none

**Comment by MMAGONA** [comment]
@IMAdft2 I will look into this!
